# Generated by Django 3.0.3 on 2020-05-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=256)),
                ('cod_departamento', models.PositiveIntegerField()),
                ('cod_subdepartamento', models.IntegerField()),
                ('cod_segmento', models.PositiveIntegerField()),
                ('cod_marca_propria', models.IntegerField()),
                ('cod_dispositivo_origem', models.PositiveIntegerField()),
                ('cod_unidade_negocio', models.PositiveIntegerField()),
                ('dia', models.DateField()),
                ('valor_calculado', models.FloatField()),
                ('percent_margem_orcada', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='meta',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='forms_app.Plataforma'),
        ),
    ]
