# Generated by Django 3.0.3 on 2020-05-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0003_plataforma_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meta',
            old_name='percent_margem_orcada',
            new_name='percentual_margem_orcada',
        ),
        migrations.AlterField(
            model_name='meta',
            name='valor_calculado',
            field=models.DecimalField(decimal_places=11, max_digits=30),
        ),
    ]
