# Generated by Django 3.0.3 on 2020-05-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0004_auto_20200518_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta1P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=256)),
                ('cod_departamento', models.PositiveIntegerField()),
                ('cod_subdepartamento', models.IntegerField()),
                ('cod_segmento', models.PositiveIntegerField()),
                ('cod_marca_propria', models.IntegerField()),
                ('cod_dispositivo_origem', models.PositiveIntegerField()),
                ('cod_unidade_negocio', models.PositiveIntegerField()),
                ('dia', models.DateField()),
                ('valor_calculado', models.DecimalField(decimal_places=11, max_digits=30)),
                ('percentual_margem_orcada', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.DeleteModel(
            name='Plataforma',
        ),
    ]
