# Generated by Django 3.0.3 on 2020-05-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0005_auto_20200518_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta1p',
            name='alcance_tv_shop',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='meta1p',
            name='valor_calc_alcance_shop',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='meta1p',
            name='percentual_margem_orcada',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
