# Generated by Django 3.0.3 on 2020-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0007_meta3p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta1p',
            name='valor_calc_alcance_shop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='meta1p',
            name='valor_calculado',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='meta3p',
            name='val_calc_alcance_mesmas_lojas_shop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='meta3p',
            name='val_calc_alcance_novas_lojas_shop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='meta3p',
            name='val_calc_mesmas_lojas',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='meta3p',
            name='val_calc_novas_lojas',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='meta3p',
            name='valor_calc_alcance_shop',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='meta3p',
            name='valor_calculado',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
