# Generated by Django 3.0.3 on 2020-05-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0008_auto_20200519_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta3p',
            name='data_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meta3p',
            name='ponto_venda',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='meta3p',
            name='val_calc_mesmas_lojas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='meta3p',
            name='val_calc_novas_lojas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='meta3p',
            name='valor_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
